---
title: "LSTAT2170 - Project"
author: "Mathieu"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(comment = "")
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

```{r}
# clean variables
rm(list = ls())
```

### Load libraries
```{r}
library(astsa)
library(mgcv)
library(simts)

library(fpp2)
library(seasonal)

library(tidyverse)
library(zoo)
library(cowplot)

library(gt)
```

```{r}
source("utils/FonctionsSeriesChrono.r")
source("utils/model_selection.r")
```

### Import data

Mean monthly air temperature (Deg. C) in Recife (Brazil) during 1986-1995.
```{r}
data <- read.table("dataset/recife.txt")
```

### Preliminary analysis

```{r}
temp_ts <- gts(
  data, 
  start = 1986, 
  freq = 12, 
  unit_ts = "°C",
  name_ts = "Air temperature",
  name_time = "Year",
  data_name = "Mean monthly air temperature in Recife (Brazil)"
)

plot(temp_ts)

temp_ts <- ts(data, start = 1986, frequency = 12)

temp_ts %>%
  autoplot() +
  labs(
    x = "Year",
    y = "Air temperature (°C)",
    title = "Mean monthly air temperature in Recife (Brazil)"
  ) +
  theme_minimal()
```
```{r}
temp_ts <- ts(data, start = 1986, frequency = 12)

# autoplot(temp_ts) + xlab("Year") + ylab("Air temperature (°C)") + ggtitle("Mean monthly temperature in Recife (Brazil)")

temp_ts %>% 
  decompose(type="additive") %>% 
  autoplot() +
  xlab("Year") +
  ggtitle("Classical decomposition of air temperature time serie") +
  theme_minimal()

temp_ts %>%
  seas() %>%
  autoplot() +
  xlab("Year") +
  ggtitle("Classical decomposition of air temperature time serie")
```

```{r}
temp_ts %>%
  ggseasonplot(year.labels = TRUE, year.labels.left = TRUE) +
  ylab("Air temperature (°C)") +
  ggtitle("Seasonal plot for mean air temperature in Recife (Brazil)") +
  theme_minimal()
```

### Box Jenkins analysis

Seasonal difference
```{r}
temp_ts_no_season <- diff(temp_ts, lag = 12)

t <- seq(from = 1986 + 1/12, by = 1/12, length = length(temp_ts_no_season))
reg_line <- tslm(temp_ts_no_season ~ t)

temp_ts_no_season %>%
  autoplot() +
    geom_abline(
      slope = reg_line$coefficients[2],
      intercept = reg_line$coefficients[1],
      color = "red"
    ) +
    xlab("Year") +
    ylab("Seasonally differenced air temperature (°C)") +
    ggtitle("Deseasonalized mean monthly temperature in Recife (Brazil)") +
    theme_minimal()
```

Trend difference
```{r}
temp_ts_no_season_no_trend <- diff(temp_ts_no_season, lag = 1)

t <- seq(from = 1986 + 1/12, by = 1/12, length = length(temp_ts_no_season_no_trend))
reg_line <- tslm(temp_ts_no_season_no_trend ~ t)

temp_ts_no_season_no_trend %>%
  autoplot() +
    geom_abline(
        slope = reg_line$coefficients[2],
        intercept = reg_line$coefficients[1],
        color = "red"
      ) +
    xlab("Year") +
    ylab("Doubly differenced air temperature (°C)") +
    ggtitle("Deseasonalized and detrended mean monthly temperature in Recife (Brazil)") +
    theme_minimal()
```

```{r}
temp_ts_diff <- temp_ts_no_season_no_trend
```

### ACF and PACF plots

Yearly dependence
```{r}
acf <- ggAcf(temp_ts_diff, lag.max = 96) +
  ggtitle("PACF on a yearly basis")
pacf <- ggPacf(temp_ts_diff, lag.max = 96) +
  ggtitle("PACF on a yearly basis")

plot_grid(acf, pacf, ncol = 2)
```

```{r}
acf <- ggAcf(temp_ts_diff, lag.max = 12) +
  ggtitle("ACF on a monthly basis")
pacf <- ggPacf(temp_ts_diff, lag.max = 12) +
  ggtitle("PACF on a monthly basis")

plot_grid(acf, pacf, ncol = 2)
```

### Model selection

```{r}
model_selection_df <- select.sarima(
  temp_ts,
  d = 1, 
  D = 1,
  max.p = 4,
  max.q = 6,
  max.P = 1,
  max.Q = 1,
  season = 12
) 

n_models <- nrow(model_selection_df)

model_selection_df %>%
  slice_min(n = round(n_models / 10), order_by = AIC) %>%
  gt %>%
  tab_header(
    title = "SARIMA model selection"
  ) #%>%
  #gtsave("report/figures/box_jenkins/sarima_model_selection.png")
```

### Model validation

```{r}
model1 <- Arima(
  temp_ts, 
  order = c(0, 1, 2), 
  seasonal = list(order = c(0, 1, 1), period = 12), 
  method = "ML"
)

model2 <- Arima(
  temp_ts,
  order = c(0, 1, 2),
  seasonal = list(order = c(1, 1, 1), period = 12),
  method = "ML"
)

model3 <- Arima(
  temp_ts,
  order = c(1, 1, 1),
  seasonal = list(order = c(0, 1, 1), period = 12),
  method = "ML"
)
```

#### Coefficients significance

```{r}
coefficients.significance(model1)
coefficients.significance(model2)
coefficients.significance(model3)
```

#### Residuals analysis

```{r}
checkresiduals(model1)
```

```{r}
checkresiduals(model3)
```

#### Prediction power

```{r}
n <- length(temp_ts)
first80 <- floor(n * 0.8)

pred_power_model1 <- predictive.power(
  temp_ts,
  order = c(0, 1, 2), 
  seasonal = list(order = c(0, 1, 1), period = 12)
)

pred_power_model3 <- predictive.power(
  temp_ts,
  order = c(1, 1, 1),
  seasonal = list(order = c(0, 1, 1), period = 12)
)
```

```{r}
temp_ts_last_2years <- ts(temp_ts[((n-24)+1):n], start = 1994, frequency = 12)

temp_ts_last_2years %>%
  autoplot(linetype = "dotted") +
    geom_line(data = pred_power_model1$data, aes(x = time, y = fitted, colour = "model 1")) +
    geom_line(data = pred_power_model3$data, aes(x = time, y = fitted, colour = "model 3")) +
    scale_color_manual(name = "SARIMA models", values = c("model 1" = "orange", "model 3" = "darkblue")) +
    labs(
      x = "Date",
      y = "Air temperature (°C)",
      title = "Prediction power for mean monthly temperature in Recife (Brazil)"
    ) +
    theme_minimal()
```

```{r}
date <- zoo::as.Date(temp_ts_last_2years)

compare_ts <- data.frame(
  date = date,
  data = temp_ts_last_2years,
  model1 = pred_power_model1$data$fitted,
  model3 = pred_power_model3$data$fitted
) %>%
  gather(key = "series", value = "values", -date)

ggplot(compare_ts, aes(x = date, y = values, color = series)) +
  geom_line() + 
  scale_color_manual(
    values = c("data" = "black", "model1" = "orange", "model3" = "darkblue"),
    labels = c("data" = "data", "model1"= "model 1", "model3" = "model 3")
  ) +
  scale_linetype_manual(values = c("data" = "dashed", "model1" = "solid", "model3"= "solid")) +
  scale_size_manual(values = c("data" = 1.2, "model1" = 1.0, "model3" = 1.0)) +
  labs(
      x = "Date",
      y = "Air temperature (°C)",
      title = "Prediction power for mean monthly temperature in Recife (Brazil)",
      color = "Series"
    ) +
  theme_minimal()
```

```{r}
data.frame(
  "model_1" = round(pred_power_model1$mse, 3),
  "model_3" = round(pred_power_model3$mse, 3)
) %>%
  gt() %>%
  tab_header({
    title = "MSE comparison of the SARIMA models"
  }) #%>%
  #gtsave("report/figures/box_jenkins/predictive_power_mse.png")
```
### Forecasting

```{r}
prediction <- model3 %>% forecast(h = 12)

combined_data <- data.frame(
  Date = c(time(temp_ts), time(prediction$mean)),
  Temperature = c(temp_ts, prediction$mean),
  Upper = c(rep(NA, length(temp_ts)), prediction$upper[, 2]),
  Lower = c(rep(NA, length(temp_ts)), prediction$lower[, 2]),
  Type = c(rep("Data", length(temp_ts)), rep("Forecast", 12))
)

ggplot(combined_data, aes(x = Date, y = Temperature)) +
  geom_line(aes(color = Type)) +
  geom_ribbon(aes(ymin = Lower, ymax = Upper), fill = "lightblue", alpha = 0.3) +
  scale_color_manual(values = c("Data" = "black", "Forecast" = "blue")) +
  labs(
    title = "Forecast of mean monthly temperature in Recife (Brazil) for the next 12 months",
    subtitle = "Forecast made with a SARIMA model",
    x = "Year", 
    y = "Air temperature (°C)"
  ) + 
  theme_minimal()
```

```{r}
prediction <- ets(temp_ts) %>% forecast(h = 12)

combined_data <- data.frame(
  Date = c(time(temp_ts), time(prediction$mean)),
  Temperature = c(temp_ts, prediction$mean),
  Upper = c(rep(NA, length(temp_ts)), prediction$upper[, 2]),
  Lower = c(rep(NA, length(temp_ts)), prediction$lower[, 2]),
  Type = c(rep("Data", length(temp_ts)), rep("Forecast", 12))
)

ggplot(combined_data, aes(x = Date, y = Temperature)) +
  geom_line(aes(color = Type)) +
  geom_ribbon(aes(ymin = Lower, ymax = Upper), fill = "lightblue", alpha = 0.3) +
  scale_color_manual(values = c("Data" = "black", "Forecast" = "blue")) +
  labs(
    title = "Forecast of mean monthly temperature in Recife (Brazil) for the next 12 months", 
    subtitle = "Forecast made with Holt Winters' seasonal method",
    x = "Year", 
    y = "Air temperature (°C)"
  ) + 
  theme_minimal()
```
